import os
import logging
from typing import List, Optional, Dict, Any
from reportlab.lib.pagesizes import letter, A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import black, white, gray, blue, navy, red, green, lightgrey
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from PIL import Image as PILImage
import io

logger = logging.getLogger(__name__)

class PDFBuilder:
    '''Builder for creating PDF documents'''
    
    def __init__(self, output_dir: str = "./generated/pdf"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
    
    def _create_custom_styles(self):
        '''Create custom paragraph styles'''
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=navy,
            alignment=TA_CENTER,
            spaceAfter=24,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=black,
            spaceAfter=12,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomSubheading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=gray,
            spaceAfter=8,
            fontName='Helvetica'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=black,
            alignment=TA_JUSTIFY,
            spaceAfter=8,
            leading=14,
            fontName='Helvetica'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBullet',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=black,
            leftIndent=20,
            bulletIndent=10,
            spaceAfter=4,
            leading=13,
            fontName='Helvetica'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SpeakerNotes',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=gray,
            alignment=TA_LEFT,
            spaceAfter=8,
            leading=11,
            fontName='Helvetica-Oblique'
        ))
        
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=gray,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
    
    def create_pdf(
        self,
        title: str,
        topic: str,
        slides: List[Dict[str, Any]],
        filename: str = "presentation.pdf",
        style: str = "professional"
    ) -> str:
        output_path = os.path.join(self.output_dir, filename)
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        story.extend(self._create_title_page(title, topic))
        story.append(PageBreak())
        
        for i, slide in enumerate(slides, 1):
            story.extend(self._create_slide_page(slide, i, len(slides)))
            if i < len(slides):
                story.append(PageBreak())
        
        story.append(Spacer(1, 0.5 * inch))
        
        doc.build(story)
        logger.info(f"PDF saved to: {output_path}")
        
        return output_path
    
    def _create_title_page(self, title: str, topic: str) -> List:
        story = []
        story.append(Spacer(1, 2 * inch))
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph(f"Topic: {topic}", self.styles['CustomSubheading']))
        story.append(Spacer(1, 0.3 * inch))
        
        from datetime import datetime
        date_str = datetime.now().strftime("%B %d, %Y")
        story.append(Paragraph(f"Generated: {date_str}", self.styles['CustomSubheading']))
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph("Generated by Vynetra AI", self.styles['CustomSubheading']))
        return story
    
    def _create_slide_page(self, slide: Dict[str, Any], number: int, total: int) -> List:
        story = []
        
        header_text = f"Slide {number} of {total}"
        story.append(Paragraph(header_text, self.styles['Footer']))
        story.append(Spacer(1, 0.1 * inch))
        
        title = slide.get('title', f'Slide {number}')
        story.append(Paragraph(title, self.styles['CustomHeading']))
        story.append(Spacer(1, 0.1 * inch))
        
        content = slide.get('content', '')
        if content:
            story.append(Paragraph(content, self.styles['CustomBody']))
            story.append(Spacer(1, 0.1 * inch))
        
        bullet_points = slide.get('bullet_points', [])
        if bullet_points:
            for point in bullet_points:
                bullet_text = f"• {point}"
                story.append(Paragraph(bullet_text, self.styles['CustomBullet']))
            story.append(Spacer(1, 0.1 * inch))
        
        diagrams = slide.get('diagrams', [])
        if diagrams:
            for diagram_path in diagrams[:1]:
                if os.path.exists(diagram_path):
                    try:
                        img = self._add_image(diagram_path, width=5*inch, height=3*inch)
                        if img:
                            story.append(img)
                            story.append(Spacer(1, 0.1 * inch))
                    except Exception as e:
                        logger.warning(f"Failed to add diagram: {e}")
        
        speaker_notes = slide.get('speaker_notes', '')
        if speaker_notes:
            story.append(Spacer(1, 0.2 * inch))
            story.append(Paragraph("Notes:", self.styles['CustomSubheading']))
            story.append(Paragraph(speaker_notes, self.styles['SpeakerNotes']))
        
        return story
    
    def _add_image(self, image_path: str, width: float, height: float):
        try:
            if not os.path.exists(image_path):
                return None
            
            with PILImage.open(image_path) as img:
                img_width, img_height = img.size
            
            aspect = img_width / img_height
            
            if width / height > aspect:
                actual_height = height
                actual_width = height * aspect
            else:
                actual_width = width
                actual_height = width / aspect
            
            return Image(image_path, width=actual_width, height=actual_height)
            
        except Exception as e:
            logger.warning(f"Failed to add image {image_path}: {e}")
            return None
    
    def create_markdown(self, title: str, slides: List[Dict[str, Any]], filename: str = "presentation.md") -> str:
        output_path = os.path.join(self.output_dir, filename)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(f"# {title}\n\n")
            
            for i, slide in enumerate(slides, 1):
                f.write(f"## Slide {i}: {slide.get('title', f'Slide {i}')}\n\n")
                
                content = slide.get('content', '')
                if content:
                    f.write(f"{content}\n\n")
                
                bullet_points = slide.get('bullet_points', [])
                if bullet_points:
                    for point in bullet_points:
                        f.write(f"- {point}\n")
                    f.write("\n")
                
                speaker_notes = slide.get('speaker_notes', '')
                if speaker_notes:
                    f.write(f"*Notes: {speaker_notes}*\n\n")
                
                f.write("---\n\n")
        
        logger.info(f"Markdown saved to: {output_path}")
        return output_path
